{% set name = "pls" %}
{% set version = "1.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pls-{{ version }}.tar.gz
  sha256: dba2682ac7d764752d09bc38c771ed0849b535356e3c3a58ee7f70edf4f8b0e0

build:
  entry_points:
    - pls = pls.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8,<4.0
  run:
    - python >=3.8,<4.0
    - pyyaml >=6.0,<7.0
    - rich >=11.1.0,<12.0.0

test:
  imports:
    - pls
    - pls.data
    - pls.enums
    - pls.fs
    - pls.models
    - pls.table
  commands:
    - pip check
    - pls --help
  requires:
    - pip

about:
  home: https://github.com/dhruvkb/pls
  doc_url: https://dhruvkb.github.io/pls/
  summary: An improved ls for developers.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
