{% set name = "pls" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pls-{{ version }}.tar.gz
  sha256: 71c5b8f693b9ed37e8342d48d95a33ca43c85816a14e6cdb42e2f580afe1d07d

build:
  entry_points:
    - pls = pls.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8,<4.0
  run:
    - python >=3.8,<4.0
    - pyyaml >=6.0,<7.0
    - rich >=12.0.0,<13.0.0

test:
  imports:
    - pls
    - pls.arg
    - pls.config
    - pls.data
    - pls.data.schema
    - pls.enums
    - pls.fs
    - pls.globals
    - pls.log
    - pls.models
    - pls.models.mixins
    - pls.output
    - pls.utils
  commands:
    - pip check
    - pls --help
  requires:
    - pip

about:
  home: https://github.com/dhruvkb/pls
  doc_url: https://dhruvkb.github.io/pls/
  summary: An improved ls for developers.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
